# Generated by Django 4.2.4 on 2023-09-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='long_description',
            field=models.TextField(default='No description provide for this poll.', max_length=2000),
        ),
        migrations.AddField(
            model_name='question',
            name='short_description',
            field=models.CharField(default='Cool kids have polls', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=100),
        ),
    ]
