# Generated by Django 4.2.4 on 2023-09-09 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_long_description_question_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='down_vote_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AddField(
            model_name='question',
            name='up_vote_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2147483647)]),
        ),
    ]
