# Generated by Django 4.2.4 on 2023-09-09 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_down_vote_count_question_up_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='participant_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2147483647)]),
        ),
    ]
