# Generated by Django 4.2.4 on 2023-09-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_sentimentvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
    ]
