# Generated by Django 4.2.4 on 2023-09-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_vote_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='down_vote_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='participant_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='up_vote_count',
        ),
    ]
