# Generated by Django 4.2.4 on 2023-09-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_question_down_vote_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='trend_score',
            field=models.FloatField(default=0.0),
        ),
    ]
